### ISSUE TITLE
When CUSTOM_LINK is `xadmin/dashboard`, the `Configuration settings` page will raise BuildError

### ISSUE THREAD

**Issue by caitinggui** [flask-dashboard/Flask-MonitoringDashboard#142]
The config file:
```
[dashboard]
APP_VERSION=1.0
CUSTOM_LINK=xadmin/dashboard
DATABASE=sqlite:////home/hadoop/project/lawplatform/logs/dashboard.db
DEFAULT_MONITOR=True
TIMEZONE=Asia/Shanghai
USERNAME=test
PASSWORD=testadmin
GUEST_USERNAME=guest
GUEST_PASSWORD="guest"
OUTLIER_DETECTION_CONSTANT=2.5
DASHBOARD_ENABLED=True
TEST_DIR=/home/hadoop/project/lawplatform/tests/
COLORS={'main':'[0,97,255]',
        'static':'[255,153,0]'}
```

The log as follow:
```
Could not build url for endpoint u'xadmin/dashboard.index'. Did you mean 'dashboard.index' instead?
Traceback (most recent call last):
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/usr/lib/python2.7/cProfile.py", line 149, in runcall
    return func(*args, **kw)
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/flask_monitoringdashboard/core/auth.py", line 19, in wrapper
    return func(*args, **kwargs)
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/flask_monitoringdashboard/views/configuration.py", line 18, in configuration
    return render_template('fmd_config.html', details=details, config=config)
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/flask_monitoringdashboard/templates/fmd_config.html", line 1, in top-level template code
    {% extends "fmd_base.html" %}
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/flask_monitoringdashboard/templates/fmd_base.html", line 35, in top-level template code
    {% block body %}
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/flask_monitoringdashboard/templates/fmd_base.html", line 109, in block "body"
    {% block content %}
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/flask_monitoringdashboard/templates/fmd_config.html", line 11, in block "content"
    <td><a href="{{ url_for(details.link + '.index') }}">/{{ details.link }}</a></td>
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/hadoop/project/lawplatform/env/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint u'xadmin/dashboard.index'. Did you mean 'dashboard.index' instead?
```

If I change CUSTOM_LINK to `dashboard`, it works well.

**Comment by FlyingBird95** [comment]
Thank you for noticing this issue. It has been fixed in #143.
