### ISSUE TITLE
upgrading

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#173]
I'm following the instructions here to upgrade to 2.0.0

    https://flask-monitoringdashboard.readthedocs.io/en/master/migration.html

The `pip upgrade` command fails with:

```
    Successfully installed Jinja2-2.10 PyJWT-1.6.4 Werkzeug-0.14.1 certifi-2018.4.16 chardet-3.0.4 decorator-4.3.0 flask-1.0.2 flask-monitoringdashboard-2.0.2 idna-2.7 jupyter-core-4.4.0 nbformat-4.4.0 numpy-1.14.5 plotly-2.7.0 psutil-5.4.6 pytz-2018.4 requests-2.19.1 six-1.11.0 sqlalchemy-1.2.8 urllib3-1.23 wtforms-2.2.1
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/usr/local/lib/python3.6/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/usr/local/lib/python3.6/site-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/idna-2.5-py3.6.egg'
```

Any idea what to do?

**Comment by mircealungu** [comment]
actually, i don't think this is related to the dashboard :)
