### ISSUE TITLE
CPU 100% when call a endpoint; QueuePool limit of size 5 overflow 10 reached

### ISSUE THREAD

**Issue by dannyeuu** [flask-dashboard/Flask-MonitoringDashboard#187]
Occur this error when any endpoint is fired

``` bas
Exception in thread Thread-161:
Traceback (most recent call last):
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/flask_monitoringdashboard/core/profiler/outlierProfiler.py", line 35, in run
    average = get_avg_duration(db_session, self._endpoint.id) * config.outlier_detection_constant
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/flask_monitoringdashboard/database/request.py", line 84, in get_avg_duration
    filter(Request.endpoint_id == endpoint_id).one()
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2947, in one
    ret = self.one_or_none()
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2917, in one_or_none
    ret = list(self)
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
    return self._execute_and_instances(context)
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3009, in _execute_and_instances
    close_with_result=True)
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3018, in _get_bind_args
    **kw
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3000, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1035, in connection
    execution_options=execution_options)
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1040, in _connection_for_bind
    engine, execution_options)
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/sqlalchemy/pool.py", line 791, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/home/tuba/anaconda3/envs/schrubles/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1189, in _do_get
    (self.size(), self.overflow(), self._timeout), code="3o7r")
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)
```

**Comment by FlyingBird95** [comment]
Hi Daniel,

Thanks for notifying this issue to us.

However, due to the summer period, it will take more time to fix this issue, but we'll let you know once this has been done.

Regards,

Patrick

**Comment by FlyingBird95** [comment]
In the mean time, if you've any idea what causes this issue, feel free to help us ;)

Or even better, solve the issue and send a PR to our development branch.

Thanks in advance,

Patrick

**Comment by saravanakesavan** [comment]
Hi @FlyingBird95 

any update on this issue?
