### ISSUE TITLE
ZeroDivision errors in logs

### ISSUE THREAD

**Issue by jlane9** [flask-dashboard/Flask-MonitoringDashboard#191]
When routes aren't very code-heavy (ex. `return "Hello World"`), I get a ZeroDivisionError in the console logs.

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File ".../venv/lib/python3.6/site-packages/flask_monitoringdashboard/core/profiler/stacktraceProfiler.py", line 77, in run
    self._on_thread_stopped()
  File ".../venv/lib/python3.6/site-packages/flask_monitoringdashboard/core/profiler/stacktraceProfiler.py", line 90, in _on_thread_stopped
    self.insert_lines_db(db_session, request_id)
  File ".../venv/lib/python3.6/site-packages/flask_monitoringdashboard/core/profiler/stacktraceProfiler.py", line 106, in insert_lines_db
    duration = val * self._duration / self._total
ZeroDivisionError: float division by zero
```

https://github.com/flask-dashboard/Flask-MonitoringDashboard/blob/4961030dc3eb4a805a06c75276248fef15a0b580/flask_monitoringdashboard/core/profiler/stacktraceProfiler.py#L105

Would checking and returning zero if self._total is zero be a valid response in this situation?
```
duration = val * self._duration / self._total if self._total != 0 else 0
```

**Comment by FlyingBird95** [comment]
Hi JLane,

thanks for your issue. Indeed, your suggested improvement seems to be correct.

Feel free to contribute to our package by forking the repository, and sending a PR to development.

Thanks in advance,

Patrick
