### ISSUE TITLE
per-version performance broken 

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#217]
**Describe the bug**
nothing is visible in the per-version performance 

**To Reproduce**
1. Go to 'https://api.zeeguu.org/dashboard'
1. Login with: "guest/vissoft"
2. Go to: https://api.zeeguu.org/dashboard/endpoint/27/versions
4. See error: no versions are to be selected, no graph is displayed

**Additional context**
Looking in the server logs I see a quite uninformative stack trace: 

```[Tue Mar 12 08:37:51.064339 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982] mod_wsgi (pid=16): Exception occurred processing WSGI script '/opt/Zeeguu-API/zeeguu_api.wsgi'.
[Tue Mar 12 08:37:51.064803 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982] Traceback (most recent call last):
[Tue Mar 12 08:37:51.064937 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
[Tue Mar 12 08:37:51.064947 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]     return self.wsgi_app(environ, start_response)
[Tue Mar 12 08:37:51.064958 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
[Tue Mar 12 08:37:51.064963 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]     response = self.handle_exception(e)
[Tue Mar 12 08:37:51.064973 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]   File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
[Tue Mar 12 08:37:51.064980 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]     return cors_after_request(app.make_response(f(*args, **kwargs)))
[Tue Mar 12 08:37:51.064989 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
[Tue Mar 12 08:37:51.064994 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]     reraise(exc_type, exc_value, tb)
[Tue Mar 12 08:37:51.065003 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
[Tue Mar 12 08:37:51.065010 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]     raise value
[Tue Mar 12 08:37:51.065018 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
[Tue Mar 12 08:37:51.065022 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]     response = self.full_dispatch_request()
[Tue Mar 12 08:37:51.065028 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1816, in full_dispatch_request
[Tue Mar 12 08:37:51.065033 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]     return self.finalize_request(rv)
[Tue Mar 12 08:37:51.065038 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1831, in finalize_request
[Tue Mar 12 08:37:51.065042 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]     response = self.make_response(rv)
[Tue Mar 12 08:37:51.065068 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1957, in make_response
[Tue Mar 12 08:37:51.065071 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982]     'The view function did not return a valid response. The'
[Tue Mar 12 08:37:51.065099 2019] [wsgi:error] [pid 16:tid 139921194698496] [remote 127.0.0.1:43982] TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
```

**Comment by bogdanp05** [comment]
The fix is now in the development branch.
It was a MySQL compatibility issue. Turns out SQLAlchemy has its limitations and not all queries are portable between RDBMSs, so I had to change the query a bit. 
We should write better tests.
