### ISSUE TITLE
Custom Graphs -related Exception

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#221]
**Describe the bug**
I found this in the apache log. 
I wonder if you can figure out from this what the problem could be.

```
[Tue Mar 12 21:33:35.975664 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502] mod_wsgi (pid=16): Exception occurred processing WSGI script '/opt/Zeeguu-API/zeeguu_api.wsgi'.
[Tue Mar 12 21:33:35.982273 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502] Traceback (most recent call last):
[Tue Mar 12 21:33:35.982421 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
[Tue Mar 12 21:33:35.982429 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]     return self.wsgi_app(environ, start_response)
[Tue Mar 12 21:33:35.982436 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
[Tue Mar 12 21:33:35.982440 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]     response = self.handle_exception(e)
[Tue Mar 12 21:33:35.982446 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]   File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
[Tue Mar 12 21:33:35.982451 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]     return cors_after_request(app.make_response(f(*args, **kwargs)))
[Tue Mar 12 21:33:35.982457 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
[Tue Mar 12 21:33:35.982460 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]     reraise(exc_type, exc_value, tb)
[Tue Mar 12 21:33:35.982479 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
[Tue Mar 12 21:33:35.982483 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]     raise value
[Tue Mar 12 21:33:35.982488 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
[Tue Mar 12 21:33:35.982492 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]     response = self.full_dispatch_request()
[Tue Mar 12 21:33:35.982497 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
[Tue Mar 12 21:33:35.982500 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]     rv = self.handle_user_exception(e)
[Tue Mar 12 21:33:35.982506 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]   File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
[Tue Mar 12 21:33:35.982509 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]     return cors_after_request(app.make_response(f(*args, **kwargs)))
[Tue Mar 12 21:33:35.982514 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
[Tue Mar 12 21:33:35.982518 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]     reraise(exc_type, exc_value, tb)
[Tue Mar 12 21:33:35.982523 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
[Tue Mar 12 21:33:35.982526 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]     raise value
[Tue Mar 12 21:33:35.982531 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
[Tue Mar 12 21:33:35.982535 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]     rv = self.dispatch_request()
[Tue Mar 12 21:33:35.982540 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
[Tue Mar 12 21:33:35.982543 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Mar 12 21:33:35.982549 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]   File "/usr/local/lib/python3.6/site-packages/flask_monitoringdashboard/core/auth.py", line 39, in wrapper
[Tue Mar 12 21:33:35.982552 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]     return func(*args, **kwargs)
[Tue Mar 12 21:33:35.982558 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]   File "/usr/local/lib/python3.6/site-packages/flask_monitoringdashboard/views/custom.py", line 16, in custom_graphs
[Tue Mar 12 21:33:35.982561 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502]     return jsonify([row2dict(row) for row in get_custom_graphs()])
[Tue Mar 12 21:33:35.982595 2019] [wsgi:error] [pid 16:tid 140063353276160] [remote 127.0.0.1:49502] TypeError: 'NoneType' object is not iterable

```

**To Reproduce**
don't know yet.

**Comment by mircealungu** [comment]
@FlyingBird95 - this is your code, right?

**Comment by FlyingBird95** [comment]
Hi Mircea,

thanks for notifying the issue. I think that it is again a MySql issue, as explained here: https://github.com/pallets/flask-sqlalchemy/issues/315#issuecomment-106994503

However, I've updated the code and I think that the issue shouldn't appear anymore. Please have a look at this branch: https://github.com/flask-dashboard/Flask-MonitoringDashboard/tree/issue221

Best,

Patrick

**Comment by bogdanp05** [comment]
^ I already merged and deleted the branch, so the link doesn't work. Here is the PR #222

**Comment by mircealungu** [comment]
Nice! Tak!
M.

**Comment by mircealungu** [comment]
Dank u wel I meant... too many languages :)
