### ISSUE TITLE
config.cfg not applied after changing PASSWORD in config.cfg

### ISSUE THREAD

**Issue by majinman** [flask-dashboard/Flask-MonitoringDashboard#309]
**Describe the bug**
I followed documentation. To change login account for dashboard, I generated config.cfg and set that file like below.
But it didn't work. It seems that application find config.cfg because when I type wrong filename, the error occurs.

```
application = Flask(__name__, template_folder='admin/templates')
dashboard.config.init_from(file='/config.cfg')
dashboard.bind(application)
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS 10.14.3]
 - FMD Version [e.g. 2.1.4]

**Additional context**

**Comment by FlyingBird95** [comment]
Hey @majinman ,

Thanks for your issue. In order to find out what went wrong with your configuration, I would like to check the following two things:

- Is the configuration that you're using the equivalent to our example configuration file, that you can find here?: https://github.com/flask-dashboard/Flask-MonitoringDashboard/blob/master/config.cfg 
- It seems that you're using an absolute path `file=/config.cfg`. Have you tried to put the config file in your repository-root folder, and using a relative path? `file=config.cfg`.

Let me know if anything helps,

Kind regards,

Patrick

**Comment by majinman** [comment]
Thanks for replying @FlyingBird95 

- Yes, it is the same file as file you uploaded.
- config.cfg is in root folder. And when I set path as '/config.cfg', I got an error 

```
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    dashboard.config.init_from(file='./config.cfg')
  File "/Users/ethan/.virtualenvs/serendipity/lib/python3.6/site-packages/flask_monitoringdashboard/core/config/__init__.py", line 128, in init_from
    self.version = parse_version(parser, 'dashboard', self.version)
  File "/Users/ethan/.virtualenvs/serendipity/lib/python3.6/site-packages/flask_monitoringdashboard/core/config/parser.py", line 24, in parse_version
    git_file = (open(os.path.join(git, 'HEAD')).read().rsplit(': ', 1)[1]).rstrip()
FileNotFoundError: [Errno 2] No such file or directory: '/<path to your project>/.git/HEAD'
```

So I use /config.cfg then, flask app starts well. However, config.cfg not applied

**Comment by FlyingBird95** [comment]
Hey @majinman ,

Thanks for your stack trace. It seems that you haven't configured the file correctly.

Try to replace line 3 `GIT=/<path to your project>/.git/` with the actual location of your git folder. Someting like `GIT=/Users/ethan/your-repo/.git/`.

Let me know if it works,

Patrick

**Comment by majinman** [comment]
Thanks @FlyingBird95 
It works! But is it possible to set config variable using object? like flask config.
As you know, project root directory path get different when I deploy project on Production Server.
