### ISSUE TITLE
Error with request.data being MultiDict in version.py

### ISSUE THREAD

**Issue by KevinPayravi** [flask-dashboard/Flask-MonitoringDashboard#356]
I got the dashboard working with my API (love it!). However, while loading the `User-Focused Multi-Version Performance` and `IP-Focused Multi-Version Performance` views, the graph fails to load and I get the following error in the backend:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_monitoringdashboard/core/auth.py", line 39, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_monitoringdashboard/views/version.py", line 108, in version_ip
    data = json.loads(request.data)['data']
  File "/usr/local/lib/python3.7/dist-packages/flask/json/__init__.py", line 253, in loads
    return _json.loads(s, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
```

In the browser, I see this in the console:

`Possibly unhandled rejection: {"data":"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n","status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/version_user/4","data":{"data":{"versions":["1.0"],"users":["112ce023-7111-4a82-92e2-dc8d4319389b"]}},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"INTERNAL SERVER ERROR","xhrStatus":"complete"}
`

From what I can gather, what's happening is that at [L78 in version.py](https://github.com/flask-dashboard/Flask-MonitoringDashboard/blob/master/flask_monitoringdashboard/views/version.py#L78) (or line 49 when dealing with an incoming request) it attempts to perform a `json.loads` on a `request.data` that's of type `MultiDict([])` (which should [actually be a string](https://flask.palletsprojects.com/en/1.1.x/api/#flask.Request.data) from what I understand, leading to the error). I've confirmed it's `MultiDict([])` by doing a print of `request.data` in my dashboard configuration.

Dashboard configuration/instantiation:
```
def configure_dashboard(app):
    def group_by_user():
        print(request.data) # This outputs MultiDict([])
        if request.headers.get('X-API-KEY'):
            return request.headers.get('X-API-KEY')
        elif request.args.get('api_key'):
            return request.args.get('api_key', None)

    dashboard.config.group_by = group_by_user
    dashboard.config.init_from(file=DASH_CONFIGS)
    dashboard.bind(app)
configure_dashboard(app)
```

Any ideas what may be causing this issue? Also to note, I originally set up my project with Python 3.8, but I downgraded to 3.7 after seeing this error and noticing that the project is listed as being compatible through 3.7. Thank you!

**Comment by KevinPayravi** [comment]
Ugh, figured it out - it's because I instantiated the app as `app = FlaskAPI(__name__)` instead of `app = Flask(__name__)` 🙃
