### ISSUE TITLE
numpy missing

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#94]
the latest version of the dashboard fails with: 
i did `pip install -r requirements.txt` but i think the dependency is not in there.
can you fix this?

```
[Sat Apr 28 00:04:13.676574 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763] mod_wsgi (pid=13140): Target WSGI script '/home/mircea/zee/http/api/zeeguu_api.wsgi' cannot be loaded as Python module.
[Sat Apr 28 00:04:13.676650 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763] mod_wsgi (pid=13140): Exception occurred processing WSGI script '/home/mircea/zee/http/api/zeeguu_api.wsgi'.
[Sat Apr 28 00:04:13.677812 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763] Traceback (most recent call last):
[Sat Apr 28 00:04:13.677887 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763]   File "/home/mircea/zee/http/api/zeeguu_api.wsgi", line 14, in <module>
[Sat Apr 28 00:04:13.677899 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763]     from zeeguu_api.app import app as application
[Sat Apr 28 00:04:13.677917 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763]   File "/home/mircea/zee/http/api/zeeguu_api/app.py", line 43, in <module>
[Sat Apr 28 00:04:13.677926 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763]     dashboard.bind(app=app, blue_print=api)
[Sat Apr 28 00:04:13.677946 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763]   File "/usr/local/lib/python3.6/site-packages/Flask_MonitoringDashboard-1.12.0-py3.6.egg/flask_monitoringdashboard/__init__.py", line 64, in bind
[Sat Apr 28 00:04:13.677955 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763]     import flask_monitoringdashboard.views
[Sat Apr 28 00:04:13.677977 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763]   File "/usr/local/lib/python3.6/site-packages/Flask_MonitoringDashboard-1.12.0-py3.6.egg/flask_monitoringdashboard/views/__init__.py", line 11, in <module>
[Sat Apr 28 00:04:13.677986 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763]     from . import dashboard
[Sat Apr 28 00:04:13.678005 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763]   File "/usr/local/lib/python3.6/site-packages/Flask_MonitoringDashboard-1.12.0-py3.6.egg/flask_monitoringdashboard/views/dashboard/__init__.py", line 12, in <module>
[Sat Apr 28 00:04:13.678015 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763]     from flask_monitoringdashboard.views.dashboard.endpoints import page_boxplot_per_endpoint
[Sat Apr 28 00:04:13.678055 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763]   File "/usr/local/lib/python3.6/site-packages/Flask_MonitoringDashboard-1.12.0-py3.6.egg/flask_monitoringdashboard/views/dashboard/endpoints.py", line 6, in <module>
[Sat Apr 28 00:04:13.678068 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763]     from flask_monitoringdashboard.core.utils import simplify
[Sat Apr 28 00:04:13.678087 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763]   File "/usr/local/lib/python3.6/site-packages/Flask_MonitoringDashboard-1.12.0-py3.6.egg/flask_monitoringdashboard/core/utils.py", line 4, in <module>
[Sat Apr 28 00:04:13.678096 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763]     import numpy as np
[Sat Apr 28 00:04:13.678131 2018] [wsgi:error] [pid 13140:tid 139939926939392] [remote 130.92.64.84:43763] ModuleNotFoundError: No module named 'numpy'

```

**Comment by FlyingBird95** [comment]
Fixed in https://github.com/flask-dashboard/Flask-MonitoringDashboard/commit/82d6d7116e41e37518548ad21576f2d65fdaaff1
